title = "Caracterizar"
version = "2.2.2"
author = "Sergi Sànchez"

[defaults]
debugmode = true
darkmode = true
estepa = true
txtprocess = "19176"
txtlot = "19176"
txtwafer = "2"
txtmask = "CNM004"
txttemperature = "35.0"
txthumidity = "41"

[dirs]
base = "config"
instruments = "instruments"
tests = "tests"
probers = "probers"
wafermaps = "wafermaps"
results = "results"
reports = "reports"

[files]
plot = "lecturas.txt"
process = "process.txt"
import_report = "report_import"

[mecao]
loadStart = true
host = "opter6"
port = "5432"
user = "joaquin"
database = "mecao"
password = ""
autocommit = false

[estepa]
method = "f-spread"
lna = false
autolimits = false
limmin = 0
limmax = 50
chunks = 16

[labs]
mysqlhost = "localhost"
mysqluser = "root"
mysqlpassword = "Mysql123"
mysqldatabase = "labs_new"

[reports]
title = "CAP REPORT"
subtitle = "19176"
date = "OCT 2025"
author = "Sergi Sànchez"
