title = "Caracterizar"
version = "2.1.0"
author = "Sergi Sànchez"

[defaults]
debugmode = true
darkmode = true
estepa = false
txtprocess = "14733"
txtlot = "14733"
txtwafer = "6"
txtmask = "CNM863"
txttemperature = "25.0"
txthumidity = "48"

[dirs]
base = "config"
instruments = "instruments"
tests = "tests"
probers = "probers"
wafermaps = "wafermaps"
results = "results"
reports = "reports"

[files]
plot = "lecturas.txt"
process = "process.txt"
import_report = "report_import"

[mecao]
loadStart = true
host = "opter6"
port = "5432"
user = "joaquin"
database = "mecao"
password = ""
autocommit = false

[estepa]
method = "k-sigma"
lna = false
autolimits = false
limmin = 0
limmax = 50
chunks = 16

[labs]
mysqlhost = "localhost"
mysqluser = "root"
mysqlpassword = "Mysql123"
mysqldatabase = "labs_new"

[reports]
title = "TLM REPORT"
subtitle = "18398"
date = "MAY 2025"
author = "Sergi Sànchez"
